export type TCategory =
  | "Huile"
  | "Aquarelle"
  | "Acrylique"
  | "Gouache"
  | "Tempéra"
  | "Fresque"
  | "Crayon"
  | "Fusain"
  | "Encre"
  | "Pastel"
  | "Sanguine"
  | "Craie"
  | "Photographie argentique"
  | "Photographie numérique"
  | "Photographie noir et blanc"
  | "Photographe couleur"
  | "Bronze"
  | "Pierre"
  | "Bois"
  | "Résine"
  | "Céramique"
  | "Verre"
  | "Porcelaine"
  | "Faïence"
  | "Grès"
  | "Terre cuite"
  | "Broderie"
  | "Tapisserie"
  | "Art vestimentaire"
  | "Linogravure"
  | "Eau-forte"
  | "Lithographie"
  | "Sérigraphie"
  | "Monotype"
  | "Soufflage de verre"
  | "Vitrail"
  | "Fusing"
  | "Joaillerie"
  | "Ebénisterie"
  | "Marqueterie"
  | "Ferronnerie d'art";
